class Number:
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __add__(self, other: Number | int | float) -> Number: ...
    def __sub__(self, other: Number | int | float) -> Number: ...
    def __mul__(self, other: Number | int | float) -> Number: ...
    def __truediv__(self, other: Number | int | float) -> Number: ...
    def __mod__(self, other: Number | int | float) -> Number: ...
    def __pow__(self, other: Number | int | float) -> bool: ...

class Int32(Number): ...
class UInt32(Number): ...
